# Generated by Django 5.0.7 on 2024-07-24 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'verbose_name_plural': 'Публикации'},
        ),
    ]
